CREATE TABLE products
(id int KEY NOT NULL AUTO_INCREMENT,
 name VARCHAR(30),
 sku VARCHAR(30),
 purchase_price DECIMAL(8,2),
 list_price DECIMAL(8,2),
 listing_fees DECIMAL(8,2),
 sold_price DECIMAL (8,2),
 quantity INTEGER(20),
 image VARCHAR(30),
 est_shipping_cost DECIMAL(8,2),
 actual_shipping_cost DECIMAL(8,2),
 categories VARCHAR(30),
 purchase_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 list_date TIMESTAMP NULL DEFAULT NULL,
 sold_date TIMESTAMP NULL DEFAULT NULL,
 status VARCHAR(30));
